### ISSUE TITLE
How to make view bottomSheet dismissable with on touch outside?

### ISSUE THREAD

**Issue by pedrofsn** [rubensousa/BottomSheetBuilder#22] opened 2017-10-10 13:42 UTC

**Comment by rubensousa** [comment] 2017-10-11 13:45
It should already dismiss when you click outside. This is the default behavior on bottom sheet dialogs

**Comment by pedrofsn** [comment] 2017-10-11 15:55
I show and hide using this method above:

```
private void controlarVisibilidadeSeletorImagem(boolean visivel) {
        mBehavior.setState(visivel ? BottomSheetBehavior.STATE_EXPANDED : BottomSheetBehavior.STATE_COLLAPSED);
    }
```

When bottom sheet is opened, it doesn't hide itself clicking outside.

**Comment by rubensousa** [comment] 2017-10-25 10:20
Are you using a view or a BottomSheetDialog? Only BottomSheetDialogs hide themselves when you click outside.

**Comment by pedrofsn** [comment] 2017-10-25 15:09
I'm using BottomSheetDialogFragment

**Comment by rubensousa** [comment] 2017-10-25 15:26
There's no BottomSheetDialogFragment in this library. How are you creating the BottomSheet? This library uses a BottomSheetDialog.

**Comment by SammyO** [comment] 2017-10-31 10:07
I can confirm that when using a view (instead of a BottomSheetDialog), clicking outside the dialog doesn't dismiss it.

**Comment by rubensousa** [comment] 2017-10-31 10:25
That's intended behavior. I'm closing this since it's the developer's responsibility to handle touch events in that case.

**Closed by rubensousa** 2017-10-31 10:25 UTC
Labels: help wanted
